<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GeradorSenhas.Application\GeradorSenhas.Application.csproj" />
    <ProjectReference Include="..\GeradorSenhas.Domain\GeradorSenhas.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

</Project>
